CREDIT TO ERDOS INSTITUTE, borrowed from them
# `numpy` - Skill Check

If you can solve the problems in this notebook without much difficulty you're good to go for our course!

In [1]:
import numpy as np

#### Problem 1

In a random walk a person starts at $0$ on a number line then flips a coin. If the coin is heads they take one step in the positive direction. If the coin is tails they take one step in the negative direction. This process lasts for $n$ steps.

Using `numpy` write a function to generate the coin flip outcomes and random walk path.

In [21]:
## Code here
def random_walk(n_steps):
    coin_flips_array=[]
    while n_steps>0:
        coin_flip=np.random.random()
        coin_flips_array.append(coin_flip)
        n_steps-=1
    array=np.array(coin_flips_array)
    maxes=array[array>0.5]
    mins=array[array<=0.5]
    return (len(maxes)-len(mins))
p=random_walk(88)
print(p)
print()





-12



In [20]:
## Code here










In [ ]:
## Code here










#### Problem 2

In linear regression you have a matrix $X$ of feature columns with a column of $1$s as the first column and a column vector $y$ of target values. You can then calculate the regression coefficients by calculating:
$$
(X^T X)^{-1}X^T y
$$

Write a function using `numpy` that calculates the coefficient vector when given $X$ and $y$.

Then find the coefficient vector for the following $X$ and $y$

In [6]:
X = np.concatenate([np.ones((500,1)),np.random.randn(500,4)], axis = 1)
print(np.shape(X))
y = X.dot(np.array([2,3,2,1,7]).reshape(-1,1)) + .25*np.random.randn(500,1)
from numpy.linalg import inv, eig, det

(500, 5)


In [8]:
## Code here
def calc_all(x_orig, y_orig):
    xt=calc_XT(x_orig)  #xT
    x_mult=xt.dot(x_orig)  #xtx
    x_mult_inv=inv(x_mult) #(xtx)-1
    x_dot=x_mult_inv.dot(xt) #(xtx)-1xt
    return x_dot.dot(y_orig)

print(calc_all(X,y))







[[2.01524375]
 [3.00311653]
 [1.9749738 ]
 [1.00280005]
 [6.99079167]]


In [ ]:
## Code here










In [ ]:
## Code here










#### Problem 3

Write a function that takes in an ndarray and computes the proportion of entries that are nonnegative.

In [2]:
## Code here
example=np.random.randn(20,3,5)
print(example)
def frac_non_negatives(arr):
    nneg=arr[arr>=0]
    #arr.size total number of entries
    #len(nneg) # total number of entries greater than or equal to zero
    print(len(nneg)/arr.size)
frac_non_negatives(example)









[[[-0.65057406  0.73933241  0.82734573  0.11652641  1.10951459]
  [-1.75658888 -1.2300843  -1.37393203  2.13439879  1.6596831 ]
  [-0.59810501 -0.21959171  0.60298675 -1.14262934  0.34584121]]

 [[-1.60466493  1.33747028 -0.90624402  0.45321005  0.73687164]
  [-0.25341528  0.11611142  0.42553975  0.27266725 -1.15801184]
  [ 0.13006733 -2.71521903 -0.10075227 -0.76131213  1.25503695]]

 [[ 0.01742231 -0.46205949  1.10497705  1.91792124  0.45533368]
  [ 0.14028301 -0.20261903 -1.83767339  0.22573829  0.1611964 ]
  [-0.96342403 -0.52724743 -0.539771    0.29773083  1.36533748]]

 [[-1.33612603  0.56372418 -0.69625827  0.3159509   1.17828933]
  [ 0.30400143  0.57177927  0.94999207 -0.61410633  0.35977453]
  [-0.21588567  0.89673383  0.23365221 -0.31813473 -0.00538624]]

 [[-0.60238304  0.37497418 -0.68730731 -1.12473861  0.13051284]
  [-1.57030671  0.03484297 -0.56994316 -1.4199293   0.61981383]
  [-0.47284156 -1.83458919 -0.20126427 -0.97394793 -0.15346293]]

 [[-0.11081201  1.0708714   0.

In [16]:
## Code here
test_array=np.ones((100,3))
test_array[:,0]=np.linspace(0,10,100)
test_array[:,1]=np.linspace(0,50,100)
test_array







array([[ 0.        ,  0.        ,  1.        ],
       [ 0.1010101 ,  0.50505051,  1.        ],
       [ 0.2020202 ,  1.01010101,  1.        ],
       [ 0.3030303 ,  1.51515152,  1.        ],
       [ 0.4040404 ,  2.02020202,  1.        ],
       [ 0.50505051,  2.52525253,  1.        ],
       [ 0.60606061,  3.03030303,  1.        ],
       [ 0.70707071,  3.53535354,  1.        ],
       [ 0.80808081,  4.04040404,  1.        ],
       [ 0.90909091,  4.54545455,  1.        ],
       [ 1.01010101,  5.05050505,  1.        ],
       [ 1.11111111,  5.55555556,  1.        ],
       [ 1.21212121,  6.06060606,  1.        ],
       [ 1.31313131,  6.56565657,  1.        ],
       [ 1.41414141,  7.07070707,  1.        ],
       [ 1.51515152,  7.57575758,  1.        ],
       [ 1.61616162,  8.08080808,  1.        ],
       [ 1.71717172,  8.58585859,  1.        ],
       [ 1.81818182,  9.09090909,  1.        ],
       [ 1.91919192,  9.5959596 ,  1.        ],
       [ 2.02020202, 10.1010101 ,  1.   